name:                haskell-backprop
version:             0.1.0.0
github:              "cdepillabout/haskell-backprop"
license:             BSD3
author:              "Dennis Gosnell"
maintainer:          "cdep.illabout@gmail.com"
copyright:           "Copyright (c) 2018 Dennis Gosnell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cdepillabout/haskell-backprop#readme>

dependencies:
  - base >= 4.7 && < 5
  - adjunctions
  - dependent-walrus
  - distributive
  - mono-traversable
  - singletons

library:
  source-dirs: src
